[project]
name = "amperon-weather"
version = "0.1.0"
description = "Weather data ingestion pipeline using Tomorrow.io API"
requires-python = ">=3.11"
dependencies = [
    # Data extraction and loading
    "dlt[duckdb]",
    "s3fs",
    "pyarrow",
    "fsspec",
    "sqlmesh[web]",
    "duckdb",
]

[project.optional-dependencies]
dev = [
    "pytest==8.1.1",
]

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["etl"]
